const FAQ_TEMPLATES: Record<string, string[]> = {
    'beauty': [
        'Welke behandelingen biedt u aan en voor wie zijn ze geschikt?',
        'Welke producten of merken gebruikt u tijdens behandelingen?',
        'Hoe lang duurt een gemiddelde afspraak en hoe kan ik boeken?',
        'Wat zijn uw hygiëne- en veiligheidsmaatregelen?',
        'Biedt u proef- of intakegesprekken aan voor nieuwe klanten?',
        'Kunt u resultaten laten zien van eerdere klanten (voor/na)?',
        'Welke betaalmethoden accepteert u en zijn er pakketkortingen?',
        'Heeft u ervaring met gevoelige huid of specifieke haarstructuren?',
        'Is parkeren of OV in de buurt beschikbaar voor bezoekers?',
        'Wat onderscheidt uw salon van andere in de regio?'
    ],
    'eten-drinken': [
        'Wat zijn uw populairste gerechten of specialiteiten?',
        'Biedt u vegetarische, vegan of halal opties aan?',
        'Kan ik online reserveren en biedt u bezorging of afhalen?',
        'Wat zijn de openingstijden en keukenuren?',
        'Heeft u allergeneninformatie of kunt u rekening houden met dieetwensen?',
        'Is er een terras, kinderstoel of rolstoeltoegang beschikbaar?',
        'Organiseert u acties zoals lunchdeals of menu\'s van de week?',
        'Heeft u ruimtes of arrangementen voor groepen en bedrijfsborrels?',
        'Welke betaalmethoden accepteert u?',
        'Waar kan ik recensies of foto’s van gerechten zien?'
    ],
    'gezondheid': [
        'Met welke klachten of zorgvragen kunnen cliënten bij u terecht?',
        'Heeft u BIG-registratie of andere relevante certificeringen?',
        'Hoe plan ik een eerste consult en wat kost dit?',
        'Werkt u samen met zorgverzekeraars of vergoedingen?',
        'Welke behandelingstrajecten biedt u en hoe lang duren ze gemiddeld?',
        'Hoe waarborgt u privacy en medische gegevens?',
        'Heeft u wachttijden of spoedmogelijkheden?',
        'Welke talen spreekt u in de praktijk?',
        'Is de praktijk toegankelijk voor mindervaliden en is er parkeergelegenheid?',
        'Biedt u online consulten of huisbezoeken aan?'
    ],
    'sport': [
        'Welke lessen of faciliteiten biedt uw sportschool aan?',
        'Hebt u proeflessen of introductiepakketten voor nieuwe leden?',
        'Wat zijn de openingstijden en piekmomenten?',
        'Biedt u personal training en voedingsadvies aan?',
        'Hoe flexibel zijn uw abonnementen en opzegtermijnen?',
        'Welke apparatuur of zalen zijn beschikbaar (bijv. sauna, groepsruimte)?',
        'Is er begeleiding voor beginners of revalidatie?',
        'Welke coronamaatregelen of hygiëneprotocollen hanteert u?',
        'Is er gratis parkeren of fietsstalling in de buurt?',
        'Biedt u bedrijfsfitness of teamtrainingen aan?'
    ],
    'klussen': [
        'Welke klussen of specialisaties neemt u het vaakst aan?',
        'In welke regio werkt u en hoe snel kunt u starten?',
        'Werkt u met vaste prijzen of offertes op maat?',
        'Welke keurmerken of certificaten heeft u (bijv. VCA)?',
        'Kunt u referenties of afgeronde projecten laten zien?',
        'Hoe gaat u om met garantie en nazorg?',
        'Werkt u ook buiten kantooruren of bij spoed?',
        'Welke materialen of merken raadt u aan en waarom?',
        'Regelt u ook vergunningen of afvoer van afval?',
        'Welke betaal- en factuurmogelijkheden biedt u?'
    ],
    'bouw-renovatie': [
        'Welke soorten bouw- of renovatieprojecten voert u uit?',
        'Kunt u een offerte en planning op maat leveren?',
        'Regelt u vergunningen en constructieberekeningen?',
        'Met welke onderaannemers of partners werkt u samen?',
        'Welke garanties en oplevermomenten hanteert u?',
        'Kunt u referenties of eerdere projecten tonen?',
        'Hoe beperkt u overlast voor buren en bewoners?',
        'Welke materialen en duurzame oplossingen biedt u?',
        'In welke regio bent u actief?',
        'Welke betaalcondities en termijnen gebruikt u?'
    ],
    'schoonmaak': [
        'Welke schoonmaakdiensten levert u (particulier/zakelijk)?',
        'Werkt u met vaste contracten of eenmalige opdrachten?',
        'Gebruikt u milieuvriendelijke producten en materialen?',
        'Kunt u ook glasbewassing of vloeronderhoud verzorgen?',
        'Wat zijn uw werktijden en reageert u op spoedklussen?',
        'Hoe screenen en trainen jullie medewerkers?',
        'Biedt u een tevredenheidsgarantie of hersteldienst?',
        'Welke panden of sectoren bedient u vooral?',
        'Heeft u referenties of keurmerken (bijv. VCA, ISO)?',
        'Welke betaal- en facturatiemogelijkheden zijn er?'
    ],
    'auto-vervoer': [
        'Welke diensten biedt u aan (APK, onderhoud, schadeherstel)?',
        'Werkt u met originele of universele onderdelen?',
        'Kan ik online een afspraak plannen en wat zijn de wachttijden?',
        'Heeft u vervangend vervoer of haal- en brengservice?',
        'Welke garanties geeft u op reparaties?',
        'Welke automerken of typen zijn uw specialiteit?',
        'Accepteert u zakelijke wagenparken of leaseauto\'s?',
        'Biedt u pechhulp of noodreparaties?',
        'Welke betaalmethoden accepteert u?',
        'Waar kan ik recensies of voorbeelden van werk zien?'
    ],
    'it-tech': [
        'Met welke IT- of deviceproblemen kunt u helpen?',
        'Biedt u on-site service, remote support of beide?',
        'Wat zijn uw responstijden en werkt u met service levels?',
        'Kunt u data back-up of recovery uitvoeren?',
        'Installeert en beveiligt u netwerken of Wi‑Fi?',
        'Ontwerpt u ook websites of webshops en hoe snel kan dat?',
        'Werkt u met onderhoudscontracten voor bedrijven?',
        'Hoe gaat u om met privacy en security van klantdata?',
        'Heeft u referenties in mijn branche?',
        'Welke tarieven hanteert u (uurtarief of pakketten)?'
    ],
    'zakelijk': [
        'Welke type bedrijven bedient u en wat is uw specialisme?',
        'Biedt u kennismakingsgesprekken of quick scans?',
        'Werkt u met vaste abonnementen of projectprijzen?',
        'Kunt u recente cases of resultaten delen?',
        'Hoe blijft u up-to-date met wet- en regelgeving?',
        'Welke tools of methodes gebruikt u in trajecten?',
        'Hoe verloopt de samenwerking en rapportage?',
        'In welke regio of sectoren bent u actief?',
        'Welke talen spreekt uw team?',
        'Welke garanties of kwaliteitslabels heeft u?'
    ],
    'onderwijs': [
        'Welke cursussen of trainingen biedt u aan en voor wie?',
        'Zijn er startdata, instroommomenten of online opties?',
        'Wie zijn de docenten en wat is hun ervaring?',
        'Wat zijn de slagingspercentages of resultaten?',
        'Biedt u proeflessen of intakegesprekken?',
        'Zijn er certificaten of diploma’s verbonden?',
        'Welke lesmaterialen en platforms gebruikt u?',
        'Hoe groot zijn de groepen en is er 1-op-1 begeleiding?',
        'Welke kosten en betalingsopties zijn er?',
        'Is er opleidingsbudget of STAP-/subsidie-informatie beschikbaar?'
    ],
    'kind-gezin': [
        'Welke leeftijdsgroepen of doelgroepen begeleidt u?',
        'Welke activiteiten of methodes gebruikt u?',
        'Hoe waarborgt u veiligheid en hygiëne?',
        'Heeft u VOG, EHBO of andere certificeringen?',
        'Wat zijn de openingstijden en opvangopties?',
        'Is er wachtlijst en hoe werkt inschrijving?',
        'Hoe betrekt u ouders bij de voortgang?',
        'Biedt u speciale programma’s voor behoeften of talentontwikkeling?',
        'Is er buitenruimte of speelmateriaal aanwezig?',
        'Welke tarieven en pakketten hanteert u?'
    ],
    'huisdieren': [
        'Welke dieren en diensten verzorgt u?',
        'Heeft u dierenarts-/trimcertificering of speciale opleidingen?',
        'Moet ik vooraf reserveren en hoe lang duurt een behandeling?',
        'Hoe gaat u om met angstige of speciale zorgdieren?',
        'Welke vaccinaties of documenten zijn vereist?',
        'Welke producten gebruikt u en zijn die diervriendelijk?',
        'Biedt u haal- en brengservice of huisbezoeken?',
        'Is er noodhulp of spoeddienst beschikbaar?',
        'Welke tarieven en pakketten hanteert u?',
        'Hoe kan ik foto’s of resultaten van andere klanten zien?'
    ],
    'wonen': [
        'Op welke type woningen of objecten richt u zich?',
        'Doet u verkoop, verhuur of beheer en in welke regio?',
        'Wat is uw courtage of tariefstructuur?',
        'Hoe stelt u een waardebepaling of taxatie op?',
        'Welke marketingkanalen zet u in voor een woning?',
        'Heeft u referenties of recente transacties?',
        'Hoe begeleidt u kopers of huurders tijdens het proces?',
        'Werkt u samen met hypotheek- of notarispartners?',
        'Welke documenten moet een klant aanleveren?',
        'Hoe blijft u bereikbaar tijdens avonden of weekenden?'
    ],
    'overnachten': [
        'Welke kamertypes en faciliteiten biedt u?',
        'Biedt u ontbijt, late check-out of andere extra’s?',
        'Wat zijn de in- en uitchecktijden?',
        'Is er parkeergelegenheid of shuttle service?',
        'Accepteert u huisdieren of kinderbedjes?',
        'Welke annuleringsvoorwaarden hanteert u?',
        'Biedt u zakelijke arrangementen of groepskortingen?',
        'Welke betaalmethoden accepteert u?',
        'Is er Wi‑Fi en welke snelheden mag ik verwachten?',
        'Wat onderscheidt uw locatie t.o.v. andere in de buurt?'
    ],
    'uitgaan': [
        'Welke activiteiten of evenementen biedt u momenteel?',
        'Hoe koop ik tickets en zijn er groepskortingen?',
        'Wat zijn de openingstijden en leeftijdsgrenzen?',
        'Is er horeca of catering aanwezig?',
        'Is de locatie toegankelijk voor mindervaliden?',
        'Welke veiligheids- of huisregels gelden er?',
        'Is er parkeergelegenheid of OV in de buurt?',
        'Mag ik foto’s of video maken op locatie?',
        'Zijn er arrangementen voor bedrijven of feestjes?',
        'Wat is jullie annulerings- of verplaatsingsbeleid?'
    ],
    'bruiloft-events': [
        'Welke soorten events of bruiloften organiseert u?',
        'Wat is inbegrepen in standaard pakketten en wat is maatwerk?',
        'Werkt u met vaste leveranciers (catering, foto, DJ)?',
        'Hoe ver van tevoren moet ik boeken?',
        'Welke capaciteit en opstellingen zijn mogelijk?',
        'Heeft u voorbeelden of referenties van eerdere events?',
        'Regelt u vergunningen of geluidstechniek?',
        'Wat zijn betalings- en annuleringsvoorwaarden?',
        'Hoe gaat u om met slecht weer of last-minute wijzigingen?',
        'Biedt u styling of decoratie in-house aan?'
    ],
    'cultuur': [
        'Welke tentoonstellingen, voorstellingen of workshops biedt u nu aan?',
        'Hoe koop ik tickets en zijn er kortingen?',
        'Biedt u rondleidingen of educatieve programma’s?',
        'Wat zijn de openingstijden en drukke momenten?',
        'Is de locatie toegankelijk voor mindervaliden?',
        'Mag ik foto’s of video maken?',
        'Zijn er faciliteiten zoals garderobe of café?',
        'Biedt u groeps- of schoolarrangementen?',
        'Welke talen worden ondersteund tijdens tours?',
        'Hoe blijf ik op de hoogte van nieuwe programma’s?'
    ],
    'interieur': [
        'Welke interieur- of maatwerkdiensten biedt u?',
        'Kunt u een 3D-ontwerp of moodboard leveren?',
        'Werkt u met specifieke merken of materialen?',
        'Wat zijn de gemiddelde doorlooptijden van projecten?',
        'Biedt u inmeetservice of advies aan huis?',
        'Hoe verloopt het offerte- en revisieproces?',
        'Kunt u referenties of portfolio delen?',
        'Levert u ook montage of plaatsing?',
        'Welke garanties of nazorg biedt u?',
        'In welke regio werkt u en hoe plant u afspraken?'
    ],
    'logistiek': [
        'Welke transport- of verhuisdiensten levert u?',
        'Werkt u regionaal, nationaal of internationaal?',
        'Kunt u spoed- of same-day leveringen verzorgen?',
        'Hoe verzekert u zendingen of inboedel?',
        'Beschikt u over opslag- of warehousemogelijkheden?',
        'Welke voertuigen en trackingopties gebruikt u?',
        'Hoe berekent u tarieven (gewicht, afstand, tijd)?',
        'Regelt u ook verpakking of montage op locatie?',
        'Zijn er speciale diensten voor zakelijke klanten?',
        'Welke documenten of vergunningen regelt u voor mij?'
    ],
    'juridisch': [
        'Op welke rechtsgebieden bent u gespecialiseerd?',
        'Biedt u een gratis intake of kennismaking?',
        'Hoe worden tarieven berekend (uurtarief, fixed fee)?',
        'Heeft u recente uitspraken of cases als referentie?',
        'Hoe houdt u cliënten op de hoogte tijdens een zaak?',
        'Welke talen spreekt u en werkt u ook online?',
        'Werkt u voor particulieren, bedrijven of beide?',
        'Hoe gaat u om met vertrouwelijkheid en AVG?',
        'Wat zijn uw doorlooptijden of wachttijden?',
        'Kunt u ook bemiddelen of mediëren?'
    ],
    'financieel': [
        'Welke financiële diensten biedt u (boekhouding, advies, belasting)?',
        'Biedt u vaste pakketten of uurtarieven?',
        'Werkt u met specifieke branches of bedrijfsgroottes?',
        'Kunt u helpen bij jaarrekening, BTW en loonadministratie?',
        'Hoe vaak rapporteert u en in welk format?',
        'Werkt u met online tools of dashboards?',
        'Biedt u ondersteuning bij financiering of subsidies?',
        'Welke certificeringen of registers heeft u?',
        'Hoe gaat u om met deadlines en aangiftes?',
        'Kunt u referenties van klanten delen?'
    ],
    'druk-reclame': [
        'Welke drukwerk- of signproducten levert u?',
        'Kunt u helpen met ontwerp en DTP?',
        'Welke materialen en afwerkingen zijn mogelijk?',
        'Wat zijn de minimale oplages en levertijden?',
        'Biedt u spoedleveringen of proefdrukken?',
        'Kunt u ook montage of plaatsing verzorgen?',
        'Welke bestanden of formaten moet ik aanleveren?',
        'Heeft u voorbeelden of referenties van projecten?',
        'Welke kleurprofielen en kwaliteitscontroles hanteert u?',
        'Biedt u opslag of fulfilment van voorraad?'
    ],
    'productie': [
        'Welke materialen of technieken gebruikt u in productie?',
        'Maakt u maatwerk of seriewerk, en met welke doorlooptijd?',
        'Heeft u voorbeelden of portfolio van eerdere projecten?',
        'Welke tolerantie- en kwaliteitsstandaarden hanteert u?',
        'Kunt u helpen bij ontwerp of prototyping?',
        'Welke machines en afmetingen kunt u aan?',
        'In welke sectoren of toepassingen heeft u ervaring?',
        'Wat zijn minimale afnames en levertijden?',
        'Biedt u montage, afwerking of installatie?',
        'Welke verzend- of logistieke opties zijn er?'
    ],
    'duurzaam': [
        'Welke duurzame oplossingen levert u (zonnepanelen, isolatie, warmtepomp)?',
        'Kunt u een gratis opname of offerte op locatie doen?',
        'Met welke merken en garanties werkt u?',
        'Regelt u subsidieaanvragen of energielabels?',
        'Hoe snel kan installatie plaatsvinden en hoe lang duurt het?',
        'Wat is het verwachte rendement of besparing?',
        'Hoe gaat u om met onderhoud en service achteraf?',
        'Is uw team gecertificeerd (bijv. InstallQ, NVDE)?',
        'Werkt u met monitoring of apps voor verbruik?',
        'In welke regio bent u actief?'
    ],
    'lokaal': [
        'Welke lokale producten of diensten levert u precies?',
        'Werkt u met seizoensgebonden aanbod?',
        'Waar komen uw ingrediënten of materialen vandaan?',
        'Ondersteunt u lokale initiatieven of evenementen?',
        'Hoe kan ik bestellen of lid worden?',
        'Heeft u afhaal- of bezorgopties?',
        'Welke betaalmethoden accepteert u?',
        'Zijn er proefpakketten of abonnementen beschikbaar?',
        'Hoe duurzaam is uw productie of logistiek?',
        'Waar kan ik u fysiek bezoeken?'
    ],
    'gemeenschap': [
        'Wat is de missie van uw organisatie?',
        'Welke activiteiten of programma’s organiseert u?',
        'Wie kan deelnemen en hoe schrijf ik me in?',
        'Hoe wordt de organisatie gefinancierd of ondersteund?',
        'Hoe kan ik vrijwilliger worden of doneren?',
        'Welke impact heeft u recent behaald?',
        'Met welke partners of gemeentes werkt u samen?',
        'Welke veiligheids- of gedragscodes hanteert u?',
        'Op welke locaties of wijken bent u actief?',
        'Hoe blijf ik op de hoogte van nieuws of evenementen?'
    ],
    'diensten': [
        'Welke publieke of loketdiensten kan ik hier regelen?',
        'Heb ik een afspraak nodig of kan ik langskomen?',
        'Welke documenten moet ik meenemen?',
        'Wat zijn de openingstijden en piekuren?',
        'Kan ik zaken online of telefonisch afhandelen?',
        'In welke talen kan ik geholpen worden?',
        'Is de locatie toegankelijk voor mindervaliden?',
        'Zijn er kosten of leges verbonden aan de dienst?',
        'Hoe snel ontvang ik een bevestiging of document?',
        'Waar kan ik klachten of feedback melden?'
    ],
    'fiets': [
        'Welke fietsen of services biedt u (reparatie, verkoop, e-bike)?',
        'Hebt u een wachttijd voor reparaties?',
        'Biedt u haal- en brengservice of mobiele reparatie?',
        'Welke merken of onderdelen gebruikt u het liefst?',
        'Verkoopt u tweedehands fietsen of leaseopties?',
        'Biedt u garantie op reparaties of onderdelen?',
        'Kan ik accessoires of upgrades laten monteren?',
        'Welke betaalmethoden accepteert u?',
        'Is er een proefrit mogelijk bij aankoop?',
        'Waar kan ik afspraken inplannen?'
    ],
    'winkels': [
        'Welke productcategorieën verkoopt u?',
        'Heeft u online winkel of click-and-collect?',
        'Wat zijn uw openingstijden en koopavond?',
        'Biedt u garantie of retourmogelijkheden?',
        'Welke merken of exclusieve lijnen voert u?',
        'Heeft u acties, loyalty of cadeaukaarten?',
        'Is er parkeergelegenheid of levering aan huis?',
        'Welke betaalmethoden accepteert u?',
        'Kunt u adviseren bij maat/keuze van producten?',
        'Waar kan ik klantenreviews zien?'
    ],
    'default': [
        'Welke diensten of producten levert u precies?',
        'Wie is uw ideale klant en in welke regio werkt u?',
        'Hoe plan ik een afspraak of offerte?',
        'Welke voordelen of garanties biedt u?',
        'Welke certificaten of ervaring heeft uw team?',
        'Wat zijn uw openingstijden of responstijden?',
        'Welke betaalmethoden accepteert u?',
        'Kunt u referenties of cases delen?',
        'Werkt u ook buiten reguliere uren of bij spoed?',
        'Wat onderscheidt uw bedrijf van anderen?'
    ]
};

export function getFaqTemplates(categorySlug?: string): string[] {
    if (!categorySlug) return FAQ_TEMPLATES['default'];
    const clean = categorySlug.toLowerCase();
    const match = Object.keys(FAQ_TEMPLATES).find(key => clean.includes(key));
    return FAQ_TEMPLATES[match || 'default'];
}
